# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='cateroty',
            new_name='category',
        ),
    ]
